### ISSUE TITLE
After updating, it no longer accepts the --disable-smooth-scrolling flag

### ISSUE THREAD

**Issue by ferrybig** [flathub/com.mongodb.Compass#13]
Before I updated, I could pass this flag to disable smooth scrolling, which is required for my accessibility setup.

After the update, it returns the following error:

    $ flatpak run com.mongodb.Compass --disableSmoothScrolling
    Errors while parsing Compass preferences
    Unknown option "disableSmoothScrolling" (while validating preferences from: Command line)

Updates should not make applications less accessible

**Comment by mijorus** [comment]
I am not the developer of Compass, please open a bug report here: https://github.com/mongodb-js/compass
