### ISSUE TITLE
Compass was not updated to 1.35.0 on flathub

### ISSUE THREAD

**Issue by rafaelndev** [flathub/com.mongodb.Compass#16]
I don't know how flathub updating works, but looking at the commits there is a update (264673a965c266b4a07295139c953eff11e15c68) to 1.35.0 from 3 weeks ago, but on flathub it stills on 1.34.2 from december.

Shouldn't it already be on 1.35?

**Comment by mijorus** [comment]
I've requested a new build, let's see if it works

**Comment by mijorus** [comment]
It was probably some bug from flathub, it's not the first time that is happens to

**Comment by rafaelndev** [comment]
Fixed, thanks @mijorus !

![image](https://user-images.githubusercontent.com/541719/216106646-5f557038-66a9-479d-83fe-337ca4955ba2.png)
