### ISSUE TITLE
EOL support thread

### ISSUE THREAD

**Issue by JavkhlanK** [flathub/com.mongodb.Compass#28]
I noticed this wrapper was discontinued. What exactly are the incompatibilities? I found one that starting with 1.38.0 the release file structure was slightly changed. But is that all?  
After quickly fixing the .json file to not copy `main` and to instead copy `main/MongoDB Compass-linux-x64` to `/app/main` and running a local build, the app launched normally for me.

**Comment by dominikzogg** [comment]
https://github.com/flathub/com.mongodb.Compass/pull/29

**Comment by mijorus** [comment]
this is not the first time that happens...

**Comment by dominikzogg** [comment]
@mijorus https://github.com/flathub/com.mongodb.Compass/pull/29 fixes this and updates every dependency

**Comment by mijorus** [comment]
@dominikzogg are you willing to maintain this project in the long term?

**Comment by dominikzogg** [comment]
@mijorus its my first contact with flatpak development, not sure if i am skilled enough yet

**Comment by mijorus** [comment]
I'm sorry but if that's the case, there is no point merging your PR.
Every time that Compass updates the is the possibility that something would not work or it doesn't launch at all.

Unfortunately there is absolutely no support from the Mongo Compass team, maybe I shouldn't have made this wrapper in the first place.


Unless we find a stable maintainer, 1.37.0 will be the last release for this wrapper.

**Comment by dominikzogg** [comment]
@mijorus well if the choice is to abandon it or i'll try to maintain it i am for the last, cause i use compass on a daily base.

**Comment by mijorus** [comment]
> @mijorus well if the choice is to abandon it or i'll try to maintain it i am for the last, cause i use compass on a daily base.

 All right, I'll ask for a change of ownership later today, thank you.

**Comment by mijorus** [comment]
@dominikzogg a request has been sent this morning, I'll keep you updated

**Comment by dominikzogg** [comment]
@mijorus i am in. I am on vacation this week, so chances are, that i wil start next week.

**Comment by mijorus** [comment]
Can you merge the Pr?

**Comment by mijorus** [comment]
If you have write access to the repo, you just need to merge something into master to create a new release, everything happens automatically.

Remember that you can't push directly to master, but you need to open a PR first, let the bot build the app successfully and then merge it.


Also, there is an automated script that fetches the latest release from Compass, updates the `json`  and opens a new pull request.

**Comment by dominikzogg** [comment]
@mijorus i tested and merged the PR for 1.38.2
