### ISSUE TITLE
MongoDB + drivers + Compass in flatpak

### ISSUE THREAD

**Issue by PlatonB** [flathub/com.mongodb.Compass#32]
Is it realistic to include the whole MongoDB and all official drivers (Pymongo and others) here? This would get rid of the tricky distro-specific installation of the DBMS, and also [allow MongoDB to be used in Ostree-based distros](https://github.com/containers/toolbox/issues/176#issuecomment-1379231832).

**Comment by dominikzogg** [comment]
Hi @PlatonB

I am not sure if i get this right. You want to have a flatplak which included mongodb server?
Flatpak's aren't meant to run server software but enduser (GUI applications). So even when this is possible, its completely out of scope of this repository / Flatpak package.

Regards Dominik

**Comment by PlatonB** [comment]
@dominikzogg As far as I understand, any non-enduser/under-the-hood software can be placed into runtimes. I really hope this is possible for MongoDB and its drivers.

**Comment by dominikzogg** [comment]
@PlatonB This feature request is out of scope
