### ISSUE TITLE
Saved connection will lost password after closing and opening MongoDB Compass

### ISSUE THREAD

**Issue by nocturnalmc** [flathub/com.mongodb.Compass#39]
The connection string saved in MongoDB Compass will lost it's password once the application is closed and reopened back again. This does not happen with MongoDB Compass in Windows 11. But it happen in this Flatpak version

**Comment by dominikzogg** [comment]
Hi @nocturnalmc

I am not sure if its flatpak related or a issues with the linux version at all. It also works for already stored onces.
I try to downgrade a dependency to check if its related.

https://github.com/flathub/com.mongodb.Compass/pull/40

**Comment by dominikzogg** [comment]
It seems to work, can you try it?

https://github.com/flathub/com.mongodb.Compass/pull/40#issuecomment-1657637746

**Comment by dominikzogg** [comment]
https://jira.mongodb.org/browse/COMPASS-7059

**Comment by nocturnalmc** [comment]
> It seems to work, can you try it?
> 
> [#40 (comment)](https://github.com/flathub/com.mongodb.Compass/pull/40#issuecomment-1657637746)

@dominikzogg Tested the new build and can confirm it works saving the password from connection string successfully even after closing and opening back the application

**Comment by dominikzogg** [comment]
Hi @nocturnalmc 

Thanks for testing, i merged the PR, but it can takes hours until the "release" happens, so i suggest to use the build of the PR for 24h hours then uninstall and reinstall the normal build from flathub.

**Comment by nocturnalmc** [comment]
Hi @dominikzogg thanks for the swift reply. I'll close this issue for now
