### ISSUE TITLE
Can't save passwords to kwallet6

### ISSUE THREAD

**Issue by nuzar** [flathub/com.mongodb.Compass#72]
Works on gnome with gnome keyring.

I'm not familiar with libsecret services, but a quick search in Compass repo find gnome-secret only, no kwallet. So this maybe an upstream problem.

https://github.com/mongodb-js/compass/blob/0bc694b0ba963200ad1a131c46db3b9479b6e928/packages/hadron-build/lib/target.js#L706

**Comment by nuzar** [comment]
Works if grant session dbus access permission to MongoDB compass.

**Comment by dominikzogg** [comment]
@nuzar can you test with `org.kde.kwalletd6`, cause `org.kde.\*` looks to open.

**Comment by nuzar** [comment]
> @nuzar can you test with `org.kde.kwalletd6`, cause `org.kde.\*` looks to open.
> 
> based on this article it should not be needed anyway. https://wiki.archlinux.org/title/KDE_Wallet
> 
> > Note: Since KDE Frameworks 5.97.0 KDE Wallet supports org.freedesktop.secrets DBus API and can now be used by libsecret for storing and retrieving passwords and other secrets using the Secret Service API.

Yes I have tested kwalletd6 and 5, it doesn’t work.
